import { Inter } from 'next/font/google'
import './globals.css'
import Footer from './components/footer'
import Header from './components/header'

import StoreProvider from "./StoreProvider"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  keywords: 'JS, Next.JS, React.js'
}

export default function RootLayout({ children }) {

  return (
    <StoreProvider>
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
       <Footer />
        </body>
    </html>
    </StoreProvider>
  )
}
